### ISSUE TITLE
Unused repo

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/press_kit#1]
Shall we remove this repository? It has no use.

**Comment by gavanderhoorn** [comment]
@ipa-mirb, @karinroehricht, @tmittner

**Comment by gavanderhoorn** [comment]
@chcorbato: the idea behind this repository was that it would be a place where -- after we make it public -- FTP champions and performers can find logos and copy-pastable text to use in their attributions.

So for sections in readmes, wiki pages and web sites.

By using templates (ie: includable snippets) as much as possible, we retain the possibility to change the text and layout later. An example is the snippet on the ROS wiki ([here](http://wiki.ros.org/rosin/acknowledgement)) which is already included by Ensenso on [wiki/ensenso_driver](http://wiki.ros.org/ensenso_driver).

---

Some of the files in this repository would of course be copies of what we have in `intranet`, but we cannot make `intranet` available to anyone outside the organisation (at least not without making the entire repository public), neither would be want to.

**Comment by gavanderhoorn** [comment]
Last time we discussed this repository, @ipa-mirb suggested to discuss this after @tmittner had returned from holidays IIRC.

It would be good if we can restart work on this, as we have many more FTPs started and starting. Getting all those to update any pages they may already have is not very efficient. Let's avoid that by providing them with clear instructions and make material available to them right from the start.

**Comment by Chamango90** [comment]
Can this be closed?

**Comment by chcorbato** [comment]
I guess so. Also, maybe better to completely eliminate this issue now that the repo is public. It has no value.
